global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'Alertmanager'

rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']
           labels:
             group: 'host'

  - job_name: 'b2b'
    scrape_interval: 5s
    static_configs:
         - targets: ['b2b-01.test.lab:9100']
           labels:
             group: 'targets'
         - targets: ['b2b-02.test.lab:9100']
           labels:
             group: 'targets'

  - job_name: 'host_prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['192.168.10.52:9100']
           labels:
             group: 'targets'

  - job_name: 'b2b-02_db'
    scrape_interval: 5s
    static_configs:
         - targets: ['b2b-02.test.lab:9104']
           labels:
             group: 'targets'
             alias: db

  - job_name: 'b2b-01_db'
    scrape_interval: 5s
    static_configs:
         - targets: ['b2b-01.test.lab:9104']
           labels:
             group: 'targets'
             alias: db

  - job_name: 'b2b-01_httpd'
    scrape_interval: 5s
    static_configs:
         - targets: ['b2b-01.test.lab:9117']
           labels:
             group: 'targets'
             alias: httpd

  - job_name: 'b2b-02_httpd'
    scrape_interval: 5s
    static_configs:
         - targets: ['b2b-02.test.lab:9117']
           labels:
             group: 'targets'
             alias: httpd

  - job_name: 'mssql_cluster'
    scrape_interval: 5s
    static_configs:
         - targets: ['192.168.10.52:4000']
           labels:
             group: 'targets'
             alias: mssql
